version: 2
services:
  - type: web
    name: hyper-io-game
    runtime: node
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: hyper-io-game
          property: port
    buildCommand: npm run build
