version: 2
services:
  - type: web
    name: hyper-io-game
    runtime: node
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: hyper-io-game
          property: port
    buildCommand: npm install
    rootDir: server
